leftnav:
- identifier: a346da25-9a02-4b11-bc34-ae832a6a3d37
  name: Menu 1
  pageRef: /lists/rl-3
  weight: 10
- identifier: a0c1ca3e-ebb2-44c0-a053-b19003d5ed83
  name: Menu 2
  pageRef: /pages/p4
  weight: 20
