leftnav:
- identifier: 190af9f1-5fa6-4c33-90f2-7ba320890dbb
  name: Menu 1 video gallery
  pageRef: /video_galleries/video-gallery
  weight: 10
- identifier: 41f2c865-b94a-4580-a3e4-20c256a2de17
  name: menu 3 sample video
  pageRef: /resources/sample-video_mp4
  weight: 20
